networks:
  diagrammer.net:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  front-node-modules:
  back-node-modules:

services:
  
  back-diagrammer:
    build:
      context: ./backend/build_docker/
      dockerfile: Dockerfile
    ports:
      - '${BACKEND_PORT:-3001}:3001'
    volumes:
      - ./backend:/app
      - back-node-modules:/app/node_modules
    working_dir: /app
    networks:
      - diagrammer.net
    depends_on:
      - diagrammer.db
      - redis
    env_file:
      - .env
    command: npm run start:dev
    restart: unless-stopped

  front-diagrammer:
    build:
      context: ./frontend/build_docker
      dockerfile: Dockerfile
    ports:
      - '${FRONTEND_PORT:-3000}:3000'
    volumes:
      - ./frontend:/app
      - front-node-modules:/app/node_modules
    working_dir: /app
    networks:
      - diagrammer.net
    depends_on:
      - back-diagrammer
    env_file:
      - .env
    command: npm run dev
    restart: unless-stopped

  diagrammer.db:
    image: postgres:16-alpine
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - diagrammer.net
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    networks:
      - d${REDIS_PORT:-6379}ammer.net
    volumes:
      - redis-data:/data
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - '${ADMINER_PORT:-8080}:8080'
    networks:
      - diagrammer.net
    depends_on:
      - diagrammer.db
    restart: unless-stopped
